services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ZouTzdSdxLYaLFYKrWUZUramftMTFdQZ
      MYSQL_DATABASE: railway
    ports:
      - "3307:3306"
    networks:
      - rede-api
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 10s

  api-cadastro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-cadastro
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/railway
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ZouTzdSdxLYaLFYKrWUZUramftMTFdQZ
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - rede-api

networks:
  rede-api:
    driver: bridge
