version: '3.1'
services:
  db:
    image: mysql
    container_name: vigilant_ellis
    environment:

      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3307:3306"
    volumes:
      - gustavo:/var/lib/mysql

volumes:
  gustavo:

