services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: os_bacanas
    ports:
      - "3307:3306"

  api-cadastro:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    container_name: api-cadastro
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/os_bacanas
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - db
